### ISSUE TITLE
Allow registry to be configurable to support internal private registry scenarios

### ISSUE THREAD

**Issue by calebwashburn** [cloudfoundry/hydrator#2]
Some scenarios there is not direct access to dockhub but instead proxied through an internal registry.  Registry is hardcoded and does not allow for overriding this.

**Comment by arjun024** [comment]
Have you tried setting an `HTTP_PROXY` or an `HTTPS_PROXY`? Something like https://stackoverflow.com/a/14663620/997813

**Comment by calebwashburn** [comment]
Sorry... Proxy not meaning proxy server but instead an internal docker mirror that has internet access.  This is pretty common pattern in enterprise setups where we need to be able to specify the host of docker which would point to an internal registry that mirrors (or proxies) docker hub.

**Comment by MarcPaquette** [comment]
Closing out this issue as it has been outstanding with no updates for 4 years.
